### ISSUE TITLE
Right-click menu contains "Add Step" instead of "Append" on the first item

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto#1072] opened 2024-05-13 08:05 UTC
### Describe the Bug

the contextual menu on the first step is not corresponding to the other steps. i tis usign the terminilogy "Add step" although all other are using "Append"

### Steps to Reproduce the Bug or Issue

1. create a route
2. right-click on first step

### Screenshots or Videos

![image](https://github.com/KaotoIO/kaoto/assets/1105127/9ce27f09-a2e3-43ca-a9ce-06ebe81e6221)

![image](https://github.com/KaotoIO/kaoto/assets/1105127/b305aa4d-48d5-4f90-a562-33e742862da6)

### Platform

- OS: linux
- Browser: VS Code
- Version: 2.0.0-RC1

**Comment by lhein** [comment] 2024-05-13 08:47
This is an intermediate state and we did that on purpose. Our current model handles the from in a route as a branchable step which isn't correct. This will need to be fixed after the GA.

**Comment by lordrip** [comment] 2024-12-02 11:51
This is due to `from` having a `steps` property, hence the `Add Step`. in YAML, the `from` is not a regular step like in `XML`.

**Comment by lordrip** [comment] 2024-12-02 11:51
I'm gonna close the issue as it's working as intended from the `YAML` point of view and also a better functionality is achieved through: https://github.com/KaotoIO/kaoto/pull/1673

**Closed by lordrip** 2024-12-02 11:51 UTC
Labels: bug
